### ISSUE TITLE
generate connections.py from net-/state.xml and compressors.yml

### ISSUE THREAD

**Issue by demogorgi** [demogorgi/MIP_based_gas_simulator#1]
The input file connections.py has to be generated from net-/state.xml and compressors.yml by a (ruby?-)script.

**Comment by demogorgi** [comment]
won't fix. create_netstate_Eingabedatei will be used for this.

**Comment by demogorgi** [comment]
Let's do it this way.

**Comment by demogorgi** [comment]
@Korialstrazh, I need
`compressors = gp.tuplelist([('N22', 'N23')])
`
to be in connections.py

**Comment by Korialstrazh** [comment]
connections.py contains now a tuplelist for compressors from -> to

**Comment by demogorgi** [comment]
@Korialstrazh I just used create_nestate. I think roughness still has the wrong unit. I need the value in m in the connections.py not in mm.

**Comment by Korialstrazh** [comment]
@demogorgi i forgot to push my commits.
