### ISSUE TITLE
generate nodes.py from net-/state.xml

### ISSUE THREAD

**Issue by demogorgi** [demogorgi/MIP_based_gas_simulator#2]
The input file nodes.py has to be generated from net-/state.xml by a (ruby?-)script.

**Comment by demogorgi** [comment]
won't fix. create_netstate_Eingabedatei will be used for this.

**Comment by demogorgi** [comment]
Let's do it this way.

**Comment by demogorgi** [comment]
@Korialstrazh, `"N26_aux":  [0.0, 1.01325, 105.01325],
 "N22_aux":  [0.0, 1.01325, 105.01325],
 "N23_aux":  [0.0, 1.01325, 105.01325]`

is missing in nodes.py

**Comment by Korialstrazh** [comment]
bug fixed. All nodes are added now

**Comment by demogorgi** [comment]
before the boundary nodes-comment a comma is missing:
`'N23_aux': [0.0, 1.01325]
	# boundary nodes
	'XH': [0.0, 56.01325],`
and pressureLimitsUpper is missing
`# set up nodes heights and pressure limits
nodes, heights, pressure_limits_lower, pressure_limits_upper = gp.multidict({
	# innodes
	'N22': [0.0, 1.01325],`
in the multidict

**Comment by Korialstrazh** [comment]
done
