### ISSUE TITLE
generate init_scenario.py from state.xml

### ISSUE THREAD

**Issue by demogorgi** [demogorgi/MIP_based_gas_simulator#3]
The input file init_scenario.py has to be generated from state.xml by a (ruby?-)script.

**Comment by demogorgi** [comment]
won't fix. create_netstate_Eingabedatei will be used for this.

**Comment by demogorgi** [comment]
Let's do it this way.

**Comment by demogorgi** [comment]
Let's do it this way.

**Comment by demogorgi** [comment]
@Korialstrazh, I find
`nodes, var_node_p_old_old, var_node_p_old = gp.multidict({
...
    "N20": [88.44325,                                    88.44325],
...`
in init_scenario.py but I had expected to find
`nodes, var_node_p_old_old, var_node_p_old = gp.multidict({
...
    "N20": [67.74525,                                    67.74525],
...`
as this is the value from state_sim.xml
`
<innode id='M723640990' alias='N20'>
                    <pressure value='66.732'/>
                    ...
`
plus 1.01325.

Also the flows of pipes and non-pipes don't seem to be correct with respect to state_sim.xml.

**Comment by Korialstrazh** [comment]
in the folder you sent me i see "N20": [71.01325, 71.01325] in init_scenario.py and pressure value="70.000" in state_sim.xml. Do you compare files from the same folder?
Also the eingabedat* file says, that P for N20 equals 70.0
