### ISSUE TITLE
Modifications create netstate sim

### ISSUE THREAD

**Issue by demogorgi** [demogorgi/MIP_based_gas_simulator#5]
Hi Micha,

could you please make some modifications in create_netstate after your cvacation?

1. add a new pipe between the original entry and _aux1. to do this introduce a new node _aux0
2. add two new pipes: one before and one after the flap trap _auxMin^_aux1
3. add two new pipes: both after _auxMax^_aux3
Let us talk before you approach the next two tasks!
4. Modify all pipe characteristics according to https://github.com/demogorgi/MIP_based_gas_simulator/blob/master/docs/urmel-entry.pdf
5. Modify the node characteristics according to the text in the same document

**Comment by Korialstrazh** [comment]
done. I also invited you to the create_netstate repo

**Comment by demogorgi** [comment]
ok, thanks
